version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    links:
      - zookeeper
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    links:
      - zookeeper
    depends_on:
      - zookeeper
      - kafka1
    ports:
      - 9093:9092
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    links:
      - zookeeper
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
    ports:
      - 9094:9092
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_CREATE_TOPICS: "Topic1:10:3,Topic2:20:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper_2:
    image: wurstmeister/zookeeper
    container_name: zookeeper_2
    ports:
      - 2182:2181
  kafka1_2:
    image: wurstmeister/kafka
    container_name: kafka1_2
    links:
      - zookeeper_2
    depends_on:
      - zookeeper_2
    ports:
      - 9084:9092
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_PORT: 9084
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_2:2181
      KAFKA_BROKER_ID: 0
      KAFKA_CREATE_TOPICS: "Cluser2Topic1:10:1,Cluster2Topic2:20:1:compact"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
